function loadFooter() {
    $('body').after('<footer class="container-md modal-footer">');
    $('footer').append('<h5 class="text-secondary text-opacity-50">This is the footer</h5>');
    $('footer').append('<a href="../modul5.html" class="btn btn-outline-success btn-lg">go back</a>');
}

function setTitle() {
    $('title').text('Fet-Week4-SelfStudy');
    $('body').addClass('container-lg');
}

function loadHeader() {
    let heading = document.title;
    $('head').after('<header class="container-md modal-header"></header>');
    $('header').append(`<h1 class="">${heading}</h1>`)
    $('header').append('<p class="text-secondary text-opacity-50">This header and footer are generated by jQuery</p>');
}

$(document).ready(function () {
    loadFooter();
    setTitle();
    loadHeader();
});